version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    target-branch: "main"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Europe/Bratislava"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - npm
    commit-message:
      prefix: "deps"
      include: scope

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: "main"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Europe/Bratislava"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "ci"
      include: scope
